config:
  # Modified from: https://github.com/lorenseanstewart/nextjs-mdx-blog-kit/blob/master/config/config.yml
  author: Eka
  siteName: "Eka’s Digital Garden"
  siteDescription: My digital garden in NextJS (in progress)
  baseUrl: https://ekas-nextjs-garden.vercel.app

  # Each social card type has its own size and dimensions requirements. TODO complete this.
  # OpenGraph images should be 1200x630 px.
  socialImgOg: "/og.jpg"
  socialImgTwitter: "/og.jpg"
  favicon: "/favicon.png"

  twitterHandle: "@ekafyi"
  twitterCardType: summary

  navigation:
    - { text: Home, link: / }
    - { text: Posts, link: /posts }
    - { text: Notes, link: /notes }
    - { text: Microblog, link: /microblog }

  typography:
    BASE_SIZE: 16
    RATIO: 1.125
    SCALE_FROM: -2
    SCALE_TO: 20
    SPACING: 4

  dateFormatPost: "d MMM yyyy"
