config:
  # Modified from: https://github.com/lorenseanstewart/nextjs-mdx-blog-kit/blob/master/config/config.yml
  author: Eka
  siteName: "Eka's Digital Garden"
  siteDescription: My digital garden in NextJS (in progress)
  defaultPageTitle: "Eka's Digital Garden"
  baseUrl: https://ekas-nextjs-garden.vercel.app

  # For Twitter cards, this logo must be a hosted url, not a relative path.
  # Must be square. Minimum size is 144x144; maximum size 4096x4096.
  websiteLogo: "https://cdn.auth0.com/blog/logos/nextjs-logo.png"

  twitterHandle: "@ekafyi"
  twitterCardType: summary

  navigation:
    - { text: Home, link: / }
    - { text: Posts, link: /posts }
    - { text: Microblog, link: /microblog }

  css:
    primaryColor: "#536DFE"
    accentColor: "#455A64"
    lightGray: "#eeeeee"
    backgroundColor: "#ffffff"
    black: "#333"
