export default {
  root: {
    fontFamily: "body",
    lineHeight: "body",
  },
  h1: { variant: "text.entryHeading" },
  // h2,
  // h3,
  // h4,
  // h5,
  // p,
  // a: {},
  // img: {},
  // pre: { variant: "components.code.pre" },
  // inlineCode: { variant: "components.code.inline" },
  // ol: {},
  // ul: {},
  // blockquote: { variant: "text.blockquote" },
  hr: {
    // borderTop: "none",
    // borderBottom: "8px solid",
    // borderBottomColor: "text",
    // width: "4rem",
    my: [null, null, 14],
    border: "none",
    textAlign: "center",
    "&::before": {
      content: '"☕️☕️☕️"',
      letterSpacing: "0.1em",
      fontSize: 8,
      display: "inline-block",
      transform: "translateY(-50%)",
    },
  },
  // table: {},
  // th: {},
  // td: {},
};
