export default {
  root: {
    fontFamily: "body",
    lineHeight: "body",
  },
  h1: { variant: "text.entryHeading" },
  // h2,
  // h3,
  // h4,
  // h5,
  // p,
  // a: {},
  // img: {},
  // pre: { variant: "components.code.pre" },
  // inlineCode: { variant: "components.code.inline" },
  // ol: {},
  // ul: {},
  // blockquote: {},
  // hr: {},
  // table: {},
  // th: {},
  // td: {},
};
